import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Copies the compiled ABIs into the shared package so the keeper and the web app read
 * one source of truth (the Solidity) without depending on a contracts build having run
 * in their checkout. Runs right after `hardhat build`.
 */

const CONTRACTS_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_PATH = resolve(CONTRACTS_ROOT, "../shared/src/generated/abis.ts");

const EXPORTED_CONTRACTS = [
  { artifact: "contracts/TestamentRegistry.sol/TestamentRegistry.json", exportName: "testamentRegistryAbi" },
  { artifact: "contracts/TestamentModule.sol/TestamentModule.json", exportName: "testamentModuleAbi" },
  { artifact: "contracts/interfaces/ISafe.sol/ISafe.json", exportName: "safeAbi" },
] as const;

type CompiledArtifact = { abi: unknown[] };

function readArtifactAbi(artifactPath: string): unknown[] {
  const fullPath = resolve(CONTRACTS_ROOT, "artifacts", artifactPath);
  const parsed = JSON.parse(readFileSync(fullPath, "utf8")) as CompiledArtifact;
  return parsed.abi;
}

const banner = `// Generated by packages/contracts/scripts/export-abis.ts. Do not edit by hand.
// Regenerate with: bun run --cwd packages/contracts build
`;

const blocks = EXPORTED_CONTRACTS.map(
  ({ artifact, exportName }) =>
    `export const ${exportName} = ${JSON.stringify(readArtifactAbi(artifact), null, 2)} as const;\n`,
);

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, `${banner}\n${blocks.join("\n")}`);

console.log(`[exportAbis] wrote ${OUTPUT_PATH}`);
